before_script:
  - docker version
  - docker-compose version

build:
  stage: deploy
  script:
    - sudo docker-compose down
    - sudo docker-compose build
    - sudo docker-compose up -d
    - pwd
  only:
  - main
